config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end
  root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments ,dependent: :destroy
	validates :title, presence: true;
	validates :body, presence: true;

	belongs_to :user, foreign_key: :user_id
	
	mount_uploader :image, PostImageUploader

	def editable_by?(cuser)
   	cuser && cuser == user
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    @comment.destroy

    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
      flash[:notice] = "post was successfully created"
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post)
      flash[:notice] = "post was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to root_path
    flash[:alert] = "post was successfully destroyed"
  end

  def who

  end


  private
  def post_params
    params.require(:post).permit(:image, :title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_name">
	<br>
	<strong><%= comment.name %></strong>
</div>
<div class="comment_body">
	<%= comment.body %>
</div>
<div class="comment_time">
	<%= time_ago_in_words(comment.created_at) %> Ago
</div>


<div>
	<%= link_to "Delete", post_comment_path(comment.post, comment),method: :delete,data: {confirm: "Are you sure?"}%>
	<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
	<br>
	<div>
		<%= f.label :name, "你的名字" %> 	<br>
		<%= f.text_area :name %>
	</div>

	<div>
		<%= f.label :body, "留言" %> <br>
		<%= f.text_area :body %>
	</div>
	<br>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/comments/edit.html.erb
<div id="post_wrapper">
	<h1>Edit Posts</h1>

	<%= form_for([@post, @comment]) do |f| %>
	<br>
	<div>
		<%= f.label :name, "你的名字" %> 	<br>
		<%= f.text_area :name %>
	</div>

	<div>
		<%= f.label :body, "留言" %><br>
		<%= f.text_area :body %>
	</div>
	<br>
	<div>
		<%= f.submit "送出"%>
	</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="main_content">
			<div class="sidebar">
				<div id="icon">
					<%= link_to root_path do %>
						<%= image_tag "ic2c.png", :class => "icon"%>
					<% end %>
				</div>
				<ul>
					<li class="category">WEBSITE</li>
					<li><%= link_to "Blog", root_path %></li>
				</ul>
				<ul>
					<li class="category">SOCIAL</li>
					<li><a href="https://facebook.com.tw">Facebook</a></li>
					<li><a href="https://google.com.tw">Google</a></li>
          <li><a href="https://github.com">Github</a></li>
				</ul>

				<% if !user_signed_in? %>
					<div class="log_in">
						<%= link_to "Login",new_session_path(:user) %>
					</div>
				
				<% elsif user_signed_in? %>
					<div class="log_in">
						<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
					</div>
					<div class="user_name">
						<%= current_user.email%>
					</div>
				 <% end %>
				
			</div>

			<%if user_signed_in? %>
				<div class="buttons">
					<button id="button"><%= link_to"New Posts", new_post_path %></button>
				</div>
			<% end %>
				
				<% flash.each do |name,msg|%>
					<div class = "alert"><%= msg %></div>
				<% end %>
		
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>

	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %>｜ prohibited this post from save</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>



	<div>
		<%= f.label :title, "標題"%><br>
		<%= f.text_field :title%>
	</div>
	<br>
	<div>
		<%= f.label :body, "內文"%><br>
		<%= f.text_area :body%>
	</div>
	<br>
	<div>
		<%= f.label :image, "圖片" %> <br>
		<%= f.file_field :image %>
	</div>
	<br>
	<div id = "button">
		<%= f.submit "送出"%>
	</div>
	<div id = "button">
		<%= link_to "取消", posts_path %>
	</div>
	
<% end %> 

app/views/posts/edit.html.erb
<div id="post_wrapper">
	<h1>Edit Posts</h1>

	<%= render :partial => 'form' %>
</div>

app/views/posts/index.html.erb
<div id="posts">
<% @posts.each do |jizz| %>
  <div class="post_wrap">
    <h2 class="title"><%= link_to jizz.title, post_path(jizz)%></h2>
    
    <div class = "author">posted by <%= jizz.user.email %></div>
    <div class="date"><%= jizz.created_at.strftime("%B, %d, %Y") %>
    </div>
    <% if jizz.editable_by?(current_user) %>
      <%= link_to "Edit", edit_post_path(jizz) %>
    <% end %>
  </div>
<% end %>
</div>

<%= paginate @posts %>

<br><br>

app/views/posts/new1.html.erb
<div id = "post_wrap">
  <h1>New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="title">
	<br>
	<h1><%= @post.title %></h1>
</div>
<br><br>
<div class = "date">
	posted <%= time_ago_in_words(@post.created_at) %> ago

	<% if @post.editable_by?(current_user) %>
		<%= link_to "Edit", edit_post_path(@post) %>||
		<%= link_to "Delete", post_path(@post) ,:method=> :delete, data: {confirm: "Are you sure?"}  %>
	<% end %>

</div>
<br><br>
<div class="body">
	<h2><%= @post.body %></h2>
</div>	
<br><br>

<div>
	<%= image_tag(@post.image_url.to_s) %>
</div>

<div class = "comments">
	<h2><%= @post.comments.count %>Comments</h2>
	<% @post.comments.each do |comment| %>
		<%= render comment %>
	<% end %>
<%= render 'comments/form' %>
</div>	
<%= link_to "回文章",root_path %>